### PR TITLE
Add missing semantic assertions for value comparison

### PR DESCRIPTION
**Pull request by marijn**
This PR is an extension of #12 (which should be merged first). It implements the following assert methods:
- `assertGreaterThan`
- `assertGreaterThanOrEqualTo`
- `assertLessThan`
- `assertLessThanOrEqualTo`

I'm much open to any suggestions.

### CODE REVIEW

**Comment by marijn** [comment]
I don't mean to rush you @antonkovalyov but have you had any time to look at this PR?

**Comment by valueof** [comment]
@marijn I didn't forget about your patches, I just found some bigger issues and need to address them first.

**Comment by marijn** [comment]
No problem. Let me know when I should rebase my PR.

**Comment by valueof** [comment]
I merged your other patch but when I started working on this one I realized that something in me still doesn't like the overly long assertions such as `assertLessThanOrEqualTo`. So I'm going close this patch for now—most probably I will just make an API to extend assertions. So that people could add their own methods. For example, some like QUnit-like asserts: `ok` and `equal`.

But in any case big thanks for your contributions!

**Pull request closed without merging**
