### PR TITLE
Extra (semantic) assertions (implements #10)

### PR DESCRIPTION
**Pull request by marijn**
So far I've implemented the following assertions.
- `assertUndefined`
- `assertNull`
- `assertInstanceOf`
- `assertObjectHasProperty`
- `assertArrayContainsValue`

I'm just putting it out here so you can give early feedback. I'll try to finish this tomorrow and add a few more tests. Is there any reason why you choose to return early in the assertions?

### CODE REVIEW

**Comment by marijn** [comment]
As far as I'm concerned this is ready for review :-)

**Comment by marijn** [comment]
I don't mean to rush you @antonkovalyov but have you had any time to look at this PR?

**Comment by valueof** [comment]
I usually work on Hiro on weekends—will take a look this Sunday.

**Comment by valueof** [comment]
I've applied parts of this patch in 365ae81732a6dacae31f9643be72e114a62bcef3 (hiro2 branch). Thanks!

**Pull request closed without merging**
